title: OpenKit
locale: en-US

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
- LICENSE
- README.md
- CNAME
